enabled GPL_TIMING_DRIVEN
The-OpenROAD-Project/megaboom pull request #156
Opened 2024-10-17 21:58 UTC by jeffng-or

Enable GPL_TIMING_DRIVEN. Here are some updated metrics:

- TNS (increase): -136,962,912.00 (v6 was -128,422,560.00)
- WNS (decrease): -1930.20 (v6 was -1966.33) - note that the WC path from v6 is now -1673)
- clock skew (decrease): 108.99 (v6 was 122)
- CTS latency (slight increase): 953 (v6 was 940) - clock tree still has long branch connecting to SRAM)

![wc_path](https://github.com/user-attachments/assets/7875e9d0-45bf-40e8-8882-0989c29e2ceb)

Still seeing "Routing congestion too high" error in GRT. Here's the heat map:

![routing_cong](https://github.com/user-attachments/assets/2e687503-7000-4210-b6ad-b995ef0a9139)

Artifacts exist in GCP through grt stage.

2024-10-18 05:07 UTC, oharboe commented
@jeffng-or @tspyrou

GPL_TIMING_DRIVEN=1 alone does not move the needle... miniscule benefit currently or noise even.

It takes an additional 3 hours to run...

I believe we have a few pathologies that have to be addressed and that until those are addressed, it is better to have faster turnaround times... We need a minimum clock period in the neighbourhood of 1000ps to be in the same range as commercial tools(700ps at 28nm in the SonicBOOM tapeout).

This PR:

```
$ git log -1
commit 7c64256f7ac4c08ed15ed7ae8977996116aa0da2 (HEAD)
Author: Jeff Ng <jeffng@precisioninno.com>
Date:   Thu Oct 17 14:51:16 2024 -0700

    enabled GPL_TIMING_DRIVEN
    
    Signed-off-by: Jeff Ng <jeffng@precisioninno.com>
$ bazel run BoomTile_place $(pwd)/tmp
$ tmp/make elapsed
.//logs/asap7/BoomTile/base
Log                            Elapsed seconds Peak Memory/MB
3_1_place_gp_skip_io                       543           6860
3_2_place_iop                               48           4316
3_3_place_gp                             14060          26420
3_4_place_resized                          898           9064
3_5_place_dp                              1855          26476
Total                                    17404          26476
```

main:

```
$ git who
$ bazel run BoomTile_place $(pwd)/tmp
$ tmp/make elapsed
tmp/make elapsed
.//logs/asap7/BoomTile/base
Log                            Elapsed seconds Peak Memory/MB
3_1_place_gp_skip_io                       465           6858
3_2_place_iop                               41           4316
3_3_place_gp                              3058          19050
3_4_place_resized                          736           9060
3_5_place_dp                              1498          26477
Total                                     5798          26477
```

2024-10-18 05:08 UTC, oharboe requested changes
@tspyrou improvements are in the miniscule/noise range.

50% (3 hours) increase in build times.

Leave be until other pathologies have been fixed.

2024-10-18 05:11 UTC, maliberty commented
@jeffng-or is this accurate - it seems different than what you showed me today where there was large difference.

2024-10-18 18:18 UTC, maliberty commented
@jeffng-or is the tns/wns comparison accurate too?

2024-10-18 19:54 UTC, jeffng-or commented
> @jeffng-or is the tns/wns comparison accurate too?

The TNS/WNS stats above are accurate to this run and v6, which was the change to run at 833MHz.

2024-11-02 08:02 UTC, oharboe commented
close? It is still available for study after it is closed.

2024-11-04 16:13 UTC, jeffng-or commented
closing per concerns about increasing GPL run time with minor impact to WNS

2024-11-04 16:13 UTC, closed without merging